---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 15m
  path: "apps/podinfo"
  validation: server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system