apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn: 
  - name: metallb-app
    namespace: flux-system
  interval: 10m0s
  path: ./apps/metallb/metallb/config
  prune: true
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
